aws_region            = "us-east-2"
state_file            = "kreverson-us-east-2-terraform-statefile"
environment           = "dev"
cluster_name          = "fastfood-cluster-dev"
vpc_cidr_block        = "10.1.0.0/16"
private_subnet_cidrs  = ["10.1.1.0/24", "10.1.2.0/24"]
public_subnet_cidrs   = ["10.1.101.0/24", "10.1.102.0/24"]
availability_zones    = ["us-east-2a", "us-east-2b"]
instance_type         = "t3.medium"
min_size              = 1
max_size              = 3
desired_size          = 2
