name: "DEVELOP DEPLOY"

on:
  pull_request:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    if: false
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prd
      aws-assume-role-arn: "arn:aws:iam::011528262719:role/github_actions_access"
      aws-region: "us-east-2"
      aws-statefile-s3-bucket: "kreverson-us-east-2-terraform-statefile"
      aws-lock-dynamodb-table: "kreverson-us-east-2-terraform-lock"